// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shogtxnajvaxgjrmoseu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNob2d0eG5hanZheGdqcm1vc2V1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDE2NzUsImV4cCI6MjA2MDYxNzY3NX0.6JbTM9F-3qRf6rLpzIsHgtDAx9zx2UYl8rcHA6j41AI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);